
# ~/Projekte/updi/pyupdi/pyupdi.py -d atmega4808 -c /dev/ttyUSB1  -f test00.hex
# ~/.local/bin/pymcuprog write --erase -d atmega4809 -t uart -u /dev/ttyUSB0 -f test10.hex

MCU = avr128da48
F_OSC = 32000000

subdirs =

targets += test00.hex

-include ../../Makefile.avr0.include
