
# ~/Projekte/updi/pyupdi/pyupdi.py -d tiny1614 -c /dev/ttyUSB1  -f test00.hex

MCU = attiny1614
F_OSC = 20000000

subdirs =

targets += test00.hex
targets += test01.hex
targets += test50.hex
targets += test60.hex

-include ../../Makefile.avr0.include
