
# ~/Projekte/updi/pyupdi/pyupdi.py -d atmega4808 -c /dev/ttyUSB1  -f test00.hex
#  .local/bin/pyupdi -d atmega4808 -c /dev/ttyUSB1  -f test00.hex

MCU = atmega4809
F_OSC = 20000000

subdirs =

targets += test00.hex
targets += test01.hex
targets += test02.hex
targets += test03.hex
targets += test04.hex
targets += test05.hex
targets += test06.hex
targets += test07.hex
targets += test08.hex
targets += test10.hex
targets += test11.hex

-include ../../Makefile.avr0.include
