# pymcuprog write --erase -d attiny1614 -t uart -u /dev/ttyUSB0 -f switch10.hex 

MCU = attiny1614
F_OSC = 20000000

subdirs =

#targets += test00.hex
#targets += telemetrySwitch00.hex
targets += switch10.hex

-include ../../Makefile.avr0.include
