
##### noch unklar

#####


MCU = attiny412
F_OSC = 20000000

subdirs =

targets += test00.elf
#targets += test01.elf
#targets += test02.elf
#targets += test03.elf
#targets += test04.elf
#targets += test05.elf

-include ../../../Makefile.avr0.include
