
# ~/Projekte/updi/pyupdi/pyupdi.py -d tiny1614 -c /dev/ttyUSB1  -f test00.hex

MCU = attiny1614
F_OSC = 20000000

subdirs =

targets += test00.elf test00.hex test00.S
targets += test01.elf test01.hex
targets += test10.elf test10.hex

-include ../../Makefile.avr0.include
