# -*- mode: makefile-gmake; -*-
#
# WMuCpp - Bare Metal C++ 
# Copyright (C) 2016, 2017 Wilhelm Meier <wilhelm.wm.meier@googlemail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

MCU = atmega328p
F_OSC = 16000000

subdirs =

targets +=  main.elf
targets +=  test01.elf test01.s
targets +=  test02.elf test02.s
targets +=  test03.elf test03.s
targets +=  test04.elf test04.s
targets +=  test05.elf test05.s
targets +=  test06.elf test06.s
targets +=  test07.elf test07.s
targets +=  test08.elf test08.s
targets +=  test09.elf test09.s
targets +=  test10.elf test10.s
targets +=  test11.elf test11.s

-include ../../../Makefile.include

