
# ~/.local/bin/pyupdi -d avr128da32 -c /dev/ttyUSB0 -f test00.hex
# ~/.local/bin/pymcuprog write --erase -d avr128da32 -t uart -u /dev/ttyUSB0 -f test10.hex

MCU = avr128da32
F_OSC = 32000000

subdirs =

#targets += test00.hex
#targets += test01.hex
#targets += test02.hex
#targets += test03.hex
#targets += test04.hex
#targets += test05.hex
#targets += test06.hex
#targets += test07.hex
#targets += test08.hex
#targets += test10.hex
#targets += test11.hex
#targets += test20.hex
#targets += test21.hex
#targets += test25.hex
#targets += test30.hex

targets += gimbal_sbus_01.hex
targets += gimbal_telm_01.hex
targets += servo_01.hex
targets += servo_02.hex
targets += ankerwinde_01.hex
#targets += schleppwinde_01.hex
#targets += schleppwinde_02.hex
targets += schleppwinde_03.hex
targets += steller_01.hex

-include ../../Makefile.avr0.include

