// -*- mode: adoc ; fill-column: 120 -*-
// ---- Beginn Standardheader
= Akkuweiche
Wilhelm Meier <wilhelm.wm.meier@googlemail.com>
:revnumber: 0.01
:revdate: 01.01.1970
:revremark: undefined
:lang: de
:toc:
:toc-title: Inhalt
:toclevels: 4
:numbered:
:src_numbered: 
:icons: font
:icontype: svg
:figure-caption: Abbildung
:description: Akkuweiche
:title: Akkuweiche
:sectanchors:
:sectlinks:
:experimental:
:copyright: Wilhelm Meier
:duration: 90
:source-highlighter: coderay
:coderay-css: style
:source-highlighter: pygments
:pygments-css: class
:status:
:menu:
:navigation:
:split:
:goto:
:blank:
:deckjs_theme: swiss
:showtitle:
:deckjs_transition: horizontal-slide
//:stylesdir: ./css
//:stylesheet: deckjs.css
:docinfo1:
:stem:
:customcss: css/deckjs.css
// not working
:revealjs_theme: black
:revealjs_slidenumber: true
// for attributes in link:[] macro like link:xxx[window="_blank"]
:linkattrs:
:nofooter:

:imgdir: images

//:short: // without images 

//include::license.adoc[]

== Symbolerklärung

[TIP]
Ein wichtiger allgemeiner Hinweis für den sicheren Aufbau und die sichere Bedienung. Dieser sollte durch den Anwender bachtet werden,
um einen sicheren Betrieb zu gewährleisten.

[NOTE]
Ein genereller Hinweis, der durch den Anwender beachtet werden sollte.

[IMPORTANT]
Ein technischer oder sicherheitstechnischer Hinweis, der unbedingt durch den Anwender beachtet werden muss.

[CAUTION]
Ein technischer oder sicherheitstechnischer Gefahrenhinweis, der unbedingt durch den Anwender beachtet werden muss. Zur 
Gefahrenabwendung muss der Anwender unbedingt die gegebenen Anweisungen befolgen und die beschriebenen Maßnahmen ergreifen.

== Rechtliches

Der vorliegende Bausatz wird dem Anwender für eigene Experimente überlassen. Er stellt kein Produkt im Sinne des ProdHaftG 
oder elektronisches Gerät im Sinne des ElektroG dar und wird als Gerät nicht kommerziell vertrieben. 

[IMPORTANT]
--
Die Überlassung gegen Unkostenerstattung erfolgt unter Ausschluss jeglicher Sach­mangelhaftung.

// Die Haftung wegen Arglist und Vorsatz sowie auf Schaden­ersatz wegen Körperverletzungen 
// sowie bei grober Fahr­lässig­keit oder Vorsatz bleibt unbe­rührt.

Für den vorliegenden Bausatz werden keine Funktionsgarantien gegeben. Für Schäden am Bausatz oder an damit verbundenen Geräten oder Modulen
wird keine Haftung übernommen. Gewährleistungen, Garantien und Widerrufsrechte gibt es nicht.
--

== Sicherheitshinweise

Beim Umgang mit Produkten, die mit elektrischer Spannung in Berührung kommen, müssen die gültigen VDE-Vorschriften beachtet werden, insbesondere 
VDE 0100, VDE 0550/0551, VDE 0700, VDE 0711 und VDE 0860.

Werkzeuge dürfen an Geräten, Bauteilen oder Baugruppen nur benutzt werden, wenn sichergestellt ist, dass die Geräte von der Versorgungsspannung 
getrennt sind und elektrische Ladungen, die in den im Gerät befindlichen Bauteilen gespeichert sind, vorher entladen wurden.

Spannungsführende Kabel oder Leitungen, mit denen das Gerät, das Bauteil oder die Baugruppe verbunden ist, müssen stets auf Isolationsfehler 
oder Bruchstellen untersucht werden. Bei Feststellen eines Fehlers in der Zuleitung muss das Gerät unverzüglich aus dem Betrieb genommen werden, 
bis die defekte Leitung ausgewechselt worden ist. Bei Einsatz von Bauelementen oder Baugruppen muss stets auf die strikte Einhaltung der in der 
zugehörigen Beschreibung genannten Kenndaten für elektrische Größen hingewiesen werden. Wenn aus einer vorliegenden Beschreibung für den nicht 
gewerblichen Endverbraucher nicht eindeutig hervorgeht, welche elektrischen Kennwerte für ein Bauteil oder eine Baugruppe gelten, wie eine 
externe Beschaltung durchzuführen ist oder welche externen Bauteile oder Zusatzgeräte angeschlossen werden dürfen und welche Anschlusswerte 
diese externen Komponenten haben dürfen, so muss stets ein Fachmann um Auskunft ersucht werden. Es ist vor der Inbetriebnahme eines Gerätes 
generell zu prüfen, ob dieses Gerät oder Baugruppe grundsätzlich für den Anwendungsfall, für den es verwendet werden soll, geeignet ist!

Im Zweifelsfalle sind unbedingt Rückfragen bei Fachleuten, Sachverständigen oder den Herstellern der verwendeten Baugruppen notwendig!

Bitte beachten Sie, dass Bedien- und Anschlussfehler außerhalb unseres Einflussbereiches liegen. Verständlicherweise können wir für Schäden, die 
daraus entstehen, keinerlei Haftung übernehmen. Bei Installationen und beim Umgang mit Netzspannung sind unbedingt die VDE-Vorschriften zu 
beachten. Geräte, die an einer Spannung über 35 V betrieben werden, dürfen nur vom Fachmann angeschlossen werden. In jedem Fall ist zu prüfen, 
ob der Bausatz oder die Platine für den jeweiligen Anwendungsfall und Einsatzort geeignet ist bzw. eingesetzt werden kann.

Derjenige, der eine Schaltung oder einen Bausatz aufbaut und fertigstellt oder eine Baugruppe durch Erweiterung bzw. Gehäuseeinbau 
betriebsbereit macht, gilt nach DIN VDE 0869 als Hersteller und ist verpflichtet, bei der Weitergabe des Gerätes alle Begleitpapiere 
mitzuliefern und auch seinen Namen und Anschrift anzugeben. Geräte, die aus Bausätzen selbst zusammengestellt werden, sind sicherheitstechnisch 
wie ein industrielles Produkt zu betrachten.

Für alle Personen- und Sachschäden, die aus nicht bestimmungsgemäßer Verwendung entstehen, ist nicht der Hersteller sondern der Betreiber 
verantwortlich. Bitte beachten Sie, das Bedien- und/und Anschlussfehler außerhalb unseres Einfußbereiches liegen. Verständlicherweise können wir 
für Schäden, die daraus entstehen, keinerlei Haftung übernehmen.

Jegliche Vorschriften und Vorsichtsmaßnahmen im Umgang mit elektrischen Komponenten sind vom Anwender einzuhalten.

Beachten Sie ebenfalls die Richtlinien unter <<Betrieb>>.

== Spezieller Sicherheitshinweis: Kleinteile

[CAUTION]
--
ACHTUNG: Der Bausatz enthält verschluckbare Kleinteile. Von Kindern fernhalten.
--

== Einbau 

[NOTE]
Das Modul wie auch diese Doku ist noch unvollständig und _work-in-progess_. 
Bei jeglichen Unklarheiten in dieser Funktionsbeschreibung und generellem Aufbau und Anschluß, 
unterlassen Sie den Betrieb und kontaktieren Sie den Bausatzersteller.


=== Anschluß an den Akku

Für einen ordnungsgemäßen Betrieb ist das Modul mit entsprechenden Kabeln zu versehen, die einen ausreichenden Querschnitt aufweisen (s.u.).

Die Anschlüsse `In(+)` / `Gnd` sind mit dem Akku zu verbinden.

Die Anschlüsse `Out` / `Gnd` sind mit den zu versorgenden Geräten zu verbinden.

Ein Verpolen der Anschlüsse kann zu einem Defekt führen.

=== Schutz 

Um das Modul gegen Feuchtigkeit zu schützen und glichzeitig die Schallausnbreitung nicht zu beeinträchtigen, empfielt es sich, das Modul 
mit Polyurethan-Lack-Schutzlack (z.B. Kontakt 70) zu überziehen. Bitte kleben Sie jedoch voher den Pfostenverbinder für den Kontackt, den 
Piezosummer und (falls noch nicht angelötet) die Lötringe für die Anschlußkabel ab.


== Funktion



[[Betrieb]]
== Betrieb

[TIP]
Beachten Sie unbedingt die Anweisungen unter <<first>>.

[NOTE]
Die üblichen Sicherheitsvorkehrungen im Betrieb mit ferngesteuerten Modellen, insbesonder Schiffsmodellen sind einzuhalten.

[IMPORTANT]
Beachten Sie *alle* folgenden Hinweise zum Betrieb.

[CAUTION]
Eine Verwendung des Moduls in Rennbooten ist nicht zulässig.

[CAUTION]
Das Modul darf nicht in Kontakt mit Wasser, Wasserdampf oder anderen Flässigkeiten kommen. Wasser oder Wasserdampf bzw. andere 
Flüssigkeiten können zu einem Totalausfall 
und damit zu einem Modellverlust sowie Personenschäden führen.

[CAUTION]
Das Modul verbraucht im Ruhezustand nur sehr wenig Strom. Trotzdem darf ein dauerhafter Anschluß an einen unüberwachten Akku nicht erfolgen.
Hier besteht Brandgefahr! Gefahr von Personenschäden!

[CAUTION]
Beim Betrieb ist die Erwärmung des Moduls zwingend zu überwachen! Eine Überhitzung kann zu einem Totalausfall und damit 
zu einem Modellverlust führen. Gefahr von Personenschäden!

[CAUTION]
Die Spannunsgversorgung ist Moduls ist im Betrieb zu überwachen. Bei Unterspannung kann das Modul abschalten oder bei gleichzeitiger 
hoher Stromaufnahme überhitzen und so zu einem Totalausfall 
und damit zu einem Modellverlust sowie Personenschäden führen

[CAUTION]
Die erforderlichen Kabelquerschnitte für die Verbindung mit dem Akku und auch mit dem elektrischen Verbraucher sind unbedingt einzuhalten. 
Hier besteht Brandgefahr. Gefahr von Personenschäden!

[CAUTION]
Beim Betrieb ist der maximale Stromdurchfluß zu begrenzen und zu überwachen. Ein zu langer und zu hoher Stromfluß kann zu einem Totalausfall 
und damit zu einem Modellverlust sowie Personenschäden führen.

[CAUTION]
Das Modul ist nicht kurzschlußfest. Ein Kurzschluß führt zu einem Totalausfall 
und damit zu einem Modellverlust sowie Personenschäden.

[CAUTION]
Der maximale Schaltstrom ist ist unbedingt einzuhalten und darf nicht überschritten werden. Ein zu hoher Schaltstrom kann zu einem Totalausfall 
und damit zu einem Modellverlust sowie Personenschäden führen.

[CAUTION]
Die Kapazitäten (Elkos, Siebelkos) am Ausgang des Moduls, etwa in Fahrtreglern (Stellern) für Motoren, 
dürfen 10.000µF nicht überschreiten. Zu hohe Kapazitäten können zu einem Totalausfall 
und damit zu einem Modellverlust sowie Personenschäden führen.

[CAUTION]
Das Modul darf keinen Vibrationen ausgesetzt werden. Treffen Sie entsprechende Vorkehrungen zu einem vibrationsgeschützten Einbau. Zu starke 
Vibrationen können zu einem Totalausfall und damit zu einem Modellverlust sowie Personenschäden führen.

[CAUTION]
Das Modul darf nur innerhalb eines Temperaturbereiches von -10°C bis +55°C betrieben werden. Ein Betrieb außerhalb dieses 
Bereiches kann zu einem Totalausfall und damit zu einem Modellverlust sowie Personenschäden führen.

== Aufbau 

Der Bausatz enthält die Einzelteile zum Aufbau des Moduls. 


=== Schrittweise Anleitung

Löten Sie alle Bauteile wie angegeben auf. Löten Sie auch den programmierten µC auf.

Beim Auflöten der MOSFETs ist darauf zu achten, dass die Verlötung auf der Platine mit der Rückseite der MOSFETs vollflächig erfolgt. Hierzu 
muss ein ausreichend starker Lötkolben verwendet werden. Achten Sie auch auf eine hohe Löttemperatur (400 °C) und eine kurze Lötdauer. 

[IMPORTANT]
Bei zu langer Lötdauer kann der MOSFET zerstört werden.

Pin 3 (_Source_) der MOSFETs muss mit _sehr viel_ Lötzinn aufgelötet werden. Trotzdem darauf achten, dass kein Kurzschluß zu einer 
benachbarten Leiterbahn entsteht.


ifdef::short[]

[TIP]
In der Kurzversion der Anleitung sind keine Bilder enthalten.
endif::[]

ifndef::short[]


endif::short[]

[[first]]
=== Erste Inberiebnahme

Die erste Inbetriebnahme _muss_ unbedingt

* ohne Verbraucher
* mit einem Labornetzteil mit einstellbarer Spannung und Strombegrenzung 

erfolgen. Am Ausgang des Moduls schließen Sie ein Multimeter oder eine LED mit passendem Vorwiderstand an.

Stellen Sie ein:

* Spannung: 8V
* Strombegrenzung: 50mA

Schließen Sie _erst jetzt_ das Modul eingangsseitig an das Labornetzteil an. Die Strombegrenzung des Labornetzteils _darf nicht_ 
ansprechen. Der Stromverbrauch sollte in der Anzeige zunächst nicht mehr als 2mA sein und nach drei Sekunden auf 2µA sinken.

Führen Sie erst nun die Einschalt- und Ausschaltsequenz aus und beobachten Sie die Ausgangsspannung bzw. LED. 

[CAUTION]
Bauen Sie erst dann das Modul in ein Modell ein, wenn Sie sich von der einwandfreien Funktion überzeugt haben.

== Kontakt

Anfragen: wilhelm.wm.meier@googlemail.com

