
all: bmcpp01 bmcpp02 bmcpp03

.PHONY: bmcpp01 bmcpp02 bmcpp03

bmcpp01:
	make -C bmcpp01 all

bmcpp02:
	make -C bmcpp02 all

bmcpp03:
	make -C bmcpp03 all

clean:
	make -C bmcpp01 clean
	make -C bmcpp02 clean
	make -C bmcpp03 clean
