# -*- mode: makefile-gmake; -*-
#
# WMuCpp - Bare Metal C++ 
# Copyright (C) 2016, 2017 Wilhelm Meier <wilhelm.wm.meier@googlemail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

#MCU = atmega328p
MCU = atmega1284p
F_OSC = 20000000

CPPFLAGS += -DNDEBUG

targets += shtml

targets += bm01.cc.extract

targets +=  bm01.s bm01.elf bm01.size
targets +=  bm02.s bm02.elf bm02.size
targets +=  bm03a.s bm03a.elf bm03a.size
targets +=  bm03b.s bm03b.elf bm03b.size
targets +=  bm04a.s bm04a.elf bm04a.size
targets +=  bm04b.s bm04b.elf bm04b.size
targets +=  bm05a.s bm05a.elf bm05a.size
targets +=  bm05b.s bm05b.elf bm05b.size
targets +=  bm06a.s bm06a.elf bm06a.size
targets +=  bm06b.s bm06b.elf bm06b.size
targets +=  bm07a.s bm07a.elf bm07a.size
targets +=  bm07b.s bm07b.elf bm07b.size
targets +=  bm08a.s bm08a.elf bm08a.size
targets +=  bm08b.s bm08b.elf bm08b.size
targets +=  bm09a.s bm09a.elf bm09a.size
targets +=  bm09b.s bm09b.elf bm09b.size
targets +=  bm10a.s bm10a.elf bm10a.size
targets +=  bm10b.s bm10b.elf bm10b.size
targets +=  bm11a.s bm11a.elf bm11a.size
targets +=  bm11b.s bm11b.elf bm11b.size
targets +=  bm20a.s bm20a.elf bm20a.size
targets +=  bm21a.s bm21a.elf bm21a.size
targets +=  bm30a.elf 
targets +=  bm30b.elf 
targets +=  bm40a.s bm40a.elf
targets +=  bm40b.s bm40b.elf
targets +=  bm60a.s bm60a.elf

-include ../../Makefile.include

