# -*- mode: makefile-gmake; -*-
#
# WMuCpp - Bare Metal C++ 
# Copyright (C) 2016, 2017 Wilhelm Meier <wilhelm.wm.meier@googlemail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

#MCU = attiny85
MCU = atmega328p
F_OSC = 20000000

targets +=  bm00a.s bm00a.elf
targets +=  bm01a.s bm01a.elf bm01a.size
targets +=  bm01b.s bm01b.elf bm01b.size
targets +=  bm02a.s bm02a.elf bm02a.size
targets +=  bm02b.s bm02b.elf bm02b.size
targets +=  bm03a.s bm03a.elf bm03a.size
targets +=  bm03b.s bm03b.elf bm03b.size
targets +=  bm04a.s bm04a.elf bm04a.size
targets +=  bm10a.s bm10a.elf bm10a.size
targets +=  bm11a.s bm11a.elf bm11a.size
targets +=  bm12a.s bm12a.elf bm12a.size
targets +=  bm21a.s bm21a.elf
targets +=  bm22a.s bm22a.elf
targets +=  bm23a.s bm23a.elf
targets +=  bm30a.s bm30a.elf
targets +=  bm31a.s bm31a.elf
targets +=  bm40a.s bm40a.elf
targets +=  bm50a.s bm50a.elf
targets +=  bm51a.s bm51a.elf

-include ../../Makefile.include

