
# ~/Projekte/updi/pyupdi/pyupdi.py -d tiny412 -c /dev/ttyUSB1  -f test00.hex

MCU = atmega4809
#MCU = avr128da32
F_OSC = 20000000

subdirs =

targets += test00.elf test00.hex
targets += test01.elf test01.hex

-include ../../../Makefile.avr0.include

#CC = /usr/local/bin/avr-gcc
#CXX = /usr/local/bin/avr-g++
