
# ~/Projekte/updi/pyupdi/pyupdi.py -d tiny412 -c /dev/ttyUSB1  -f test00.hex

#MCU = atmega4809
#F_OSC = 20000000
MCU = avr128da32
F_OSC = 32000000

subdirs =

#test02.hex : F_OSC = 24000000
#test20.hex : F_OSC = 28000000

#targets += test00.elf test00.hex
#targets += test01.elf test01.hex
#targets += test02.hex
#targets += test10.hex
#targets += test11.hex
#targets += test12.hex
#targets += test20.hex
#targets += test21.hex
#targets += hott00.hex
#targets += hott01.hex
#targets += test30.hex
targets += esc10_avr128_hw03.hex

-include ../../../Makefile.avr0.include

#CC = /usr/local/bin/avr-gcc
#CXX = /usr/local/bin/avr-g++
