
# ~/Projekte/updi/pyupdi/pyupdi.py -d tiny412 -c /dev/ttyUSB1  -f test00.hex

MCU = attiny412
F_OSC = 20000000

subdirs =

#targets += test00.elf test00.hex
#targets += test01.elf test01.hex
targets += test10.elf test10.hex
targets += esc_ppm_22.hex
#targets += test99.elf test99.hex

-include ../../../Makefile.avr0.include
