# -*- mode: makefile-gmake; -*-
#
# WMuCpp - Bare Metal C++ 
# Copyright (C) 2016, 2017 Wilhelm Meier <wilhelm.wm.meier@googlemail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

MCU = atmega328p
F_OSC = 20000000


targets +=  bm01a.s bm01a.elf bm01a.size
targets +=  bm01b.s bm01b.elf bm01b.size
targets +=  bm02a.s bm02a.elf bm02a.size
targets +=  bm02b.s bm02b.elf bm02b.size
targets +=  bm03a.s bm03a.elf bm03a.size
targets +=  bm04a.s bm04a.elf bm04a.size
targets +=  bm04b.s bm04b.elf bm04b.size
targets +=  bm05a.s bm05a.elf bm05a.size
targets +=  bm05b.s bm05b.elf bm05b.size
targets +=  bm06a.s bm06a.elf bm06a.size
targets +=  bm06b.s bm06b.elf bm06b.size
targets +=  bm07a.s bm07a.elf bm07a.size
targets +=  bm08a.s bm08a.elf bm08a.size
targets +=  bm10a.s bm10a.elf bm10a.size
targets +=  bm11a.s bm11a.elf bm11a.size
targets +=  bm12a.s bm12a.elf bm12a.size

-include ../../Makefile.include

CPPFLAGS += -DNDEBUG
