
# ~/Projekte/updi/pyupdi/pyupdi.py -d atmega4808 -c /dev/ttyUSB1  -f test00.hex

MCU = atmega4809
F_OSC = 20000000

subdirs =

#targets += test00.hex
#targets += test01.hex
#targets += test02.hex

-include ../../Makefile.avr0.include
