# -*- mode: makefile-gmake; -*-
#
# WMuCpp - Bare Metal C++ 
# Copyright (C) 2016, 2017 Wilhelm Meier <wilhelm.wm.meier@googlemail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

MCU = atmega328pb
F_OSC = 20000000


subdirs =

#targets += main.elf 
targets += test01.s test01.elf
targets += test02.s test02.elf
targets += test03.s test03.elf
targets += test04.s test04.elf
targets += test05.s test05.elf
targets += test06.s test06.elf
targets += test07.s test07.elf
targets += test09.s test09.elf
targets += test10.s test10.elf
targets += test11.s test11.elf

-include ../../Makefile.include
