# -*- mode: makefile-gmake; -*-
#
# WMuCpp - Bare Metal C++ 
# Copyright (C) 2016, 2017 Wilhelm Meier <wilhelm.wm.meier@googlemail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

MCU = atmega328pb
F_OSC = 20000000


subdirs =

#targets += main.elf 
#targets += test01.s test01.elf
#targets += test02.s test02.elf
#targets += test03.s test03.elf
#targets += test04.s test04.elf
#targets += test05.s test05.elf
#targets += test06.s test06.elf
#targets += test07.s test07.elf
#targets += test09.s test09.elf
#targets += test10.s test10.elf
#targets += test11.s test11.elf
#targets += test12.s test12.elf
#targets += test13.s test13.elf
#targets += test14.s test14.elf
#targets += test15.s test15.elf
#targets += test16.s test16.elf
#targets += test17.s test17.elf
#targets += test18.s test18.elf
#targets += test19.s test19.elf
#targets += test20.s test20.elf
#targets += test21.s test21.elf
#targets += test22.s test22.elf
#targets += test23.s test23.elf
#targets += test24.s test24.elf
#targets += test25.s test25.elf

targets += test100.s test100.elf

targets += test99.s test99.elf


-include ../../Makefile.include
