
#MCU = atmega328pb
#F_OSC = 16000000

#MCU = attiny85
#F_OSC = 1000000

#MCU = atmega88p
#F_OSC = 16000000

#MCU = atmega8
#F_OSC = 16000000

MCU = atmega1284p
F_OSC = 16000000

#MCU = atmega32
#F_OSC = 16000000

subdirs =

targets +=  blink.elf blink.s blink.hex
targets +=  blink_32tqfp_prog_sockel.elf blink_32tqfp_prog_sockel.s blink_32tqfp_prog_sockel.hex
targets +=  blinkc.elf blinkc.s blinkc.hex

#-include ../../Makefile.include
-include ../../Makefile.avr0.include
